name: ci
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
env:
  FORCE_COLOR: 3
concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}
jobs:
  ci:
    name: CI
    if: github.ref_type != 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install Dependencies
        run: npm clean-install
      - name: Build Project
        run: npx nr build
      - name: Run Tests
        run: npx nr test
      # - name: Upload Coverage Report
      #   uses: codecov/codecov-action@v3
