name: ci
on:
  - push
  - pull_request
env:
  FORCE_COLOR: 3
jobs:
  ci-cd:
    name: CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Prepare
        run: npm ci

      - name: Build
        run: npx nr build

      - name: Test
        run: npx nr test.passWithNoTests
        # run: npx nr test.coverage

      # - name: Upload Coverage Report
      #   run: bash <(curl -s https://codecov.io/bash)
